/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// quad 2-input NAND gate
module \7400  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = ~ (\1A  & \1B );
  assign \2Y  = ~ (\2A  & \2B );
  assign \3Y  = ~ (\3A  & \3B );
  assign \4Y  = ~ (\4A  & \4B );
endmodule

module Gated_D_Latch (
  input Clock,
  input D_set,
  input D,
  input Clk,
  output Qa_bit,
  output Q,
  output Q_not
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire Qa_bit_temp;
  wire Q_not_temp;
  wire Q_temp;
  assign s1 = ~ D_set;
  \7400  \7400_i0 (
    .\1A ( D_set ),
    .\1B ( Clock ),
    .\2A ( s1 ),
    .\2B ( Clock ),
    .GND( 1'b0 ),
    .\3A ( Qa_bit_temp ),
    .\3B ( s2 ),
    .\4A ( s3 ),
    .\4B ( s0 ),
    .VCC( 1'b1 ),
    .\1Y ( s0 ),
    .\2Y ( s2 ),
    .\3Y ( s3 ),
    .\4Y ( Qa_bit_temp )
  );
  assign Q_temp = ~ (~ (D & Clk) & Q_not_temp);
  assign Q_not_temp = ~ (Q_temp & ~ (Clk & ~ D));
  assign Qa_bit = Qa_bit_temp;
  assign Q = Q_temp;
  assign Q_not = Q_not_temp;
endmodule
