/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// hex inverter
module \7404  (
  input \1A ,
  input \2A ,
  input \3A ,
  input \4A ,
  input \5A ,
  input \6A ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y ,
  output \5Y ,
  output \6Y 
);
  assign \1Y  = ~ \1A ;
  assign \2Y  = ~ \2A ;
  assign \3Y  = ~ \3A ;
  assign \4Y  = ~ \4A ;
  assign \5Y  = ~ \5A ;
  assign \6Y  = ~ \6A ;
endmodule

// quad 2-input NAND gate
module \7400  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = ~ (\1A  & \1B );
  assign \2Y  = ~ (\2A  & \2B );
  assign \3Y  = ~ (\3A  & \3B );
  assign \4Y  = ~ (\4A  & \4B );
endmodule

module Master_Slave_D_Flip_Flop (
  input D_set,
  input Clock,
  input D,
  input Clk,
  output Q_slave,
  output Q_master,
  output Qm_not,
  output Qm,
  output Qs_not,
  output Qs
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire Q_master_temp;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire Q_slave_temp;
  wire Qm_not_temp;
  wire Qm_temp;
  wire s9;
  wire Qs_not_temp;
  wire Qs_temp;
  \7404  \7404_i0 (
    .\1A ( 1'b0 ),
    .\2A ( 1'b0 ),
    .\3A ( D_set ),
    .GND( 1'b0 ),
    .\4A ( 1'b0 ),
    .\5A ( 1'b0 ),
    .\6A ( 1'b0 ),
    .VCC( 1'b1 ),
    .\3Y ( s1 )
  );
  assign s9 = ~ Clk;
  \7400  \7400_i1 (
    .\1A ( D_set ),
    .\1B ( Clock ),
    .\2A ( s1 ),
    .\2B ( Clock ),
    .GND( 1'b0 ),
    .\3A ( s2 ),
    .\3B ( Q_master_temp ),
    .\4A ( s3 ),
    .\4B ( s0 ),
    .VCC( 1'b1 ),
    .\1Y ( s0 ),
    .\2Y ( s2 ),
    .\3Y ( s3 ),
    .\4Y ( Q_master_temp )
  );
  \7404  \7404_i2 (
    .\1A ( 1'b0 ),
    .\2A ( 1'b0 ),
    .\3A ( 1'b0 ),
    .GND( 1'b0 ),
    .\4A ( Clock ),
    .\5A ( 1'b0 ),
    .\6A ( Q_master_temp ),
    .VCC( 1'b1 ),
    .\4Y ( s4 ),
    .\6Y ( s6 )
  );
  assign Qm_temp = ~ (~ (D & Clk) & Qm_not_temp);
  assign Qm_not_temp = ~ (Qm_temp & ~ (~ D & Clk));
  assign Qs_temp = ~ (~ (Qm_temp & s9) & Qs_not_temp);
  assign Qs_not_temp = ~ (Qs_temp & ~ (~ Qm_temp & s9));
  \7400  \7400_i3 (
    .\1A ( Q_master_temp ),
    .\1B ( s4 ),
    .\2A ( s6 ),
    .\2B ( s4 ),
    .GND( 1'b0 ),
    .\3A ( s7 ),
    .\3B ( Q_slave_temp ),
    .\4A ( s8 ),
    .\4B ( s5 ),
    .VCC( 1'b1 ),
    .\1Y ( s5 ),
    .\2Y ( s7 ),
    .\3Y ( s8 ),
    .\4Y ( Q_slave_temp )
  );
  assign Q_slave = Q_slave_temp;
  assign Q_master = Q_master_temp;
  assign Qm_not = Qm_not_temp;
  assign Qm = Qm_temp;
  assign Qs_not = Qs_not_temp;
  assign Qs = Qs_temp;
endmodule
