/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

// quad 2-input NOR gate
module \7402  (
  input \1A ,
  input \1B ,
  input \2A ,
  input \2B ,
  input \3B ,
  input \3A ,
  input \4A ,
  input \4B ,
  input VCC,
  input GND,
  output \1Y ,
  output \2Y ,
  output \3Y ,
  output \4Y 
);
  assign \1Y  = ~ (\1A  | \1B );
  assign \2Y  = ~ (\2A  | \2B );
  assign \3Y  = ~ (\3A  | \3B );
  assign \4Y  = ~ (\4A  | \4B );
endmodule

module SR_Latch (
  input Set,
  input Reset,
  input R,
  input S,
  output Qa_bit,
  output Qa,
  output Qb
);
  wire s0;
  wire Qa_bit_temp;
  wire Qb_temp;
  wire Qa_temp;
  \7402  \7402_i0 (
    .\1A ( 1'b0 ),
    .\1B ( 1'b0 ),
    .\2A ( 1'b0 ),
    .\2B ( 1'b0 ),
    .GND( 1'b0 ),
    .\3A ( s0 ),
    .\3B ( Reset ),
    .\4A ( Set ),
    .\4B ( Qa_bit_temp ),
    .VCC( 1'b1 ),
    .\3Y ( Qa_bit_temp ),
    .\4Y ( s0 )
  );
  assign Qa_temp = ~ (R | Qb_temp);
  assign Qb_temp = ~ (Qa_temp | S);
  assign Qa_bit = Qa_bit_temp;
  assign Qa = Qa_temp;
  assign Qb = Qb_temp;
endmodule
