/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module \7_segment_HEX_decoder  (
  input b0,
  input b1,
  input b2,
  input b3,
  output a,
  output b,
  output c,
  output d,
  output e,
  output f,
  output g
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  assign s0 = ~ b0;
  assign s1 = ~ b1;
  assign s2 = ~ b2;
  assign s3 = ~ b3;
  assign s4 = (b0 & b1);
  assign s8 = (b2 & b3);
  assign s5 = (s0 & b1);
  assign s6 = (b0 & s1);
  assign s7 = (s0 & s1);
  assign s9 = (s2 & b3);
  assign s10 = (b2 & s3);
  assign s11 = (s2 & s3);
  assign s15 = (s4 & s8);
  assign s12 = (s6 & s11);
  assign s13 = (s4 & s10);
  assign s14 = (s7 & s8);
  assign s16 = (s6 & s10);
  assign s17 = (s6 & s8);
  assign s18 = (s5 & s11);
  assign s19 = (s4 & s9);
  assign s20 = (s4 & s11);
  assign s21 = (s12 | (s7 & s10));
  assign s22 = ((s14 | s15) | (s5 & s8));
  assign s23 = (s12 | s13);
  assign a = ((s21 | s17) | s19);
  assign b = ((s22 | s16) | ((s5 & s10) | s19));
  assign c = (s22 | s18);
  assign d = ((s21 | s13) | (s15 | (s5 & s9)));
  assign e = (((s21 | s16) | ((s6 & s9) | s20)) | s13);
  assign f = ((s23 | s17) | (s20 | s18));
  assign g = ((s23 | (s7 & s11)) | s14);
endmodule
